config/routes.rb
Knowledgebase::Application.routes.draw do
  devise_for :users

  resources :users, except: [:show] do
    get :profile, on: :collection
  end

  resources :skills do
    resources :questions do
      resources :answers
    end
  end

  root :to => 'home#index'
end

app/models/skill.rb
class Skill
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name
  field :description
  field :user_id, type: Moped::BSON::ObjectId
  field :tags, type: Array

  attr_accessible :name, :description, :tags

  belongs_to :user
  embeds_many :questions, validate: false

  validates :name, presence: true, uniqueness: true

  scope :tagged, ->(name) { where(tags: name) }

  def new?
    created_at > 3.days.ago
  end

  def prepare_tags!
    self.tags = self.tags.join(", ") if self.tags.is_a? Array
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  load_and_authorize_resource

  def index
    @skills = SkillQuery.new.find_all(params)
  end

  def new
  end

  def create
    @skill = current_user.skills.new build_params(params[:skill])
    if @skill.save
      redirect_to @skill, notice: I18n.t(:created_successfully)
    else
      render :new
    end
  end

  def show
  end

  def edit
    @skill.prepare_tags!
  end

  def update
    if @skill.update_attributes build_params(params[:skill])
      redirect_to @skill, notice: I18n.t(:updated_successfully)
    else
      @skill.prepare_tags!
      render :edit
    end
  end

  def destroy
    @skill = Skill.find params[:id]
    @skill.destroy
    redirect_to skills_path
  end

  private
  def build_params(params)
    if params[:tags].is_a? String
      params[:tags] = params[:tags].split(",").map(&:strip)
    end

    params
  end
end

app/helpers/skills_helper.rb
module SkillsHelper
  def links_to_tags(tags)
    tags.map do |tag_name|
      link_to "##{tag_name}", skills_path(tag: tag_name), :class => "tag-link"
    end.join(" ").html_safe
  end
end

app/views/skills/_form.html.haml
= simple_form_for skill, html: { class: "form-horizontal" } do |f|
  = f.input :name, input_html: { class: "input-xxlarge" }
  = f.input :description, as: :text, input_html: { class: "input-xxlarge", rows: 6 }, hint: render('answers/markdown_hint')
  = f.input :tags, input_html: { class: "input-xxlarge" }, hint: t(:csv_tags)
  .form-actions
    = f.button :submit, class: "btn btn-primary", :"disable-with" => t(:wait)

app/views/skills/_manage_buttons.html.haml
- if can? :manage, skill
  .manage-button-wrapper
    = link_to t(:delete_skill), skill, method: :delete, confirm: t(:are_you_sure), class: "manage-button"
  .manage-button-wrapper
    = link_to t(:edit_skill), edit_skill_path(skill), class: "manage-button"

app/views/skills/_menu.html.haml
%ul.nav.nav-tabs
  = menu_item t(:available_skills), skills_path
  = menu_item t(:create_new_skill), new_skill_path

  - if action == "edit"
    = menu_item @skill.name, edit_skill_path(@skill)

  - if %w(show edit_question show_question).include? action
    = menu_item @skill.name, skill_path(@skill)

    - if action == "show"
      = menu_item t(:new_questions), new_skill_question_path(@skill)

    - if action == "edit_question"
      = menu_item @question.title, edit_skill_question_path(@skill, @question)

    - if action == "show_question"
      = menu_item @question.title, skill_question_path(@skill, @question)

app/views/skills/edit.html.haml
= render 'menu', action: "edit"

.tab-content
  .tab-pane.active
    = render 'form', skill: @skill

app/views/skills/index.html.haml
= render 'menu', action: "index"

.tab-content
  .tab-pane.active
    #skills
      - @skills.each do |skill|
        .row.skill-row.clearfix
          .span1
            .skill-card
              .skill-card-inner
                .skill
                  %h4= skill.questions.count
          .span8
            .skill-info.clearfix
              = render 'skills/manage_buttons', skill: skill
              %h5
                = link_to skill.name, skill, class: "skill-link"
              %ol.unstyled.horizontal
                - if skill.new?
                  %li
                    %span.new= t(:new_skill)
                %li= l skill.created_at, format: :long
                %li.questions= link_to t(:questions), skill_path(skill, anchor: "#questions"), class: "questions-link"

              %p.description
                = markdown skill.description
              .tags.clearfix
                = succeed ":" do
                  = t(:tags)
                = links_to_tags(skill.tags)

        %hr

app/views/skills/new.html.haml
= render 'menu', action: "new"

.tab-content
  .tab-pane.active
    = render 'form', skill: @skill

app/views/skills/show.html.haml
= render 'menu', action: "show"

.tab-content
  .tab-pane.active
    %article
      .skill-header
        .row
          .span9
            = render "skills/manage_buttons", skill: @skill
            %h3
              = @skill.name
              %p.lead
                - if @skill.new?
                  %span.new= t(:new_skill)
                  |
                = l @skill.created_at, format: :long
      .skill-summary
        .row
          .span6
            %h5 Description
            %blockquote= markdown @skill.description
          .span3
            %dl.dl-horizontal
              %dt= t(:questions_count)
              %dd= @skill.questions.count
              %dt= t(:answered_questions_count)
              %dd= @skill.questions.answered.count
              %dt= t(:tags)
              %dd= links_to_tags(@skill.tags)
      #questions.questions
        - @skill.questions.each do |question|
          .row
            .span1
              .skill-card.question-card
                .skill-card-inner
                  .skill
                    %h5= question.answers.count
            .span8.question
              = render 'questions/manage_buttons', question: question
              %h5
                = link_to (question.title || question.picture), skill_question_path(@skill, question), class: "skill-link"