config/routes.rb
Knowledgebase::Application.routes.draw do
  devise_for :users

  resources :users, except: [:show] do
    get :profile, on: :collection
  end

  resources :skills do
    resources :questions do
      resources :answers
    end
  end

  root :to => 'home#index'
end

app/views/shared/_flashes.html.haml
- flash.each do |name, message|
  - css_class = name == :notice ? "alert-success" : "alert-error"
  .fade.in.alert{class: css_class}
    %button.close{:"data-dismiss" => "alert"} x
    = message

app/views/shared/_top_nav_bar.html.haml
.masthead
  %ul.nav.nav-pills.pull-right
    %li{class: ("active" if current_page? root_path)}
      = link_to t(:home), root_path
    - if can? :list, Skill
      %li{class: ("active" if current_page? skills_path)}
        = link_to t(:skills), skills_path

    - if user_signed_in?
      %li.dropdown{class: ("active" if current_page_profile?)}
        = link_to "#", id: "js-user-dropdown", class: "dropdown-toggle", role: "button", :"data-toggle" => "dropdown" do
          = current_user.username
          %b.caret
        %ul#js-user-menu.dropdown-menu{role: "menu", :"aria-labelledby" => "js-user-dropdown" }
          %li= link_to t(:profile), profile_users_path, tabindex: -1
          %li= link_to t(:edit_profile), edit_user_registration_path
      %li
        = link_to t(:sign_out), destroy_user_session_path

    - else
      %li{class: ("active" if current_page? new_user_session_path)}
        = link_to t(:already_member), new_user_session_path
      %li{class: ("active" if current_page? new_user_registration_path)}
        = link_to t(:got_invite), new_user_registration_path

  %h3.muted= "Knowledge base"