config/routes.rb
Knowledgebase::Application.routes.draw do
  devise_for :users

  resources :users, except: [:show] do
    get :profile, on: :collection
  end

  resources :skills do
    resources :questions do
      resources :answers
    end
  end

  root :to => 'home#index'
end

app/models/answer.rb
class Answer
  include Mongoid::Document
  include Mongoid::Timestamps

  field :content
  field :user_id, type: Moped::BSON::ObjectId
  field :accepted, type: Boolean, default: false
  field :rating, type: Integer, default: 0

  belongs_to :user
  embedded_in :question

  attr_accessible :content, :proof_link

  validates :content, :user_id, presence: true
  validates :rating, numericality: { only_integer: true }

  delegate :username, to: :user, prefix: true

  def skill
    question.skill
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  authorize_resource

  before_filter :find_skill
  before_filter :find_question
  before_filter :find_answer, only: [:edit, :update, :destroy]

  def create
    @answer = @answers.new params[:answer]
    @answer.user_id = current_user.id
    if @answer.save
      redirect_to skill_question_path(@skill, @question, anchor: "answers"), notice: t(:created_successfully)
    else
      render "questions/show"
    end
  end

  def edit

  end

  def update
    if @answer.update_attributes params[:answer]
      redirect_to skill_question_path(@skill, @question, anchor: "answer_#{@answer.id}"), notice: t(:updated_successfully)
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
  end

  private
  def find_skill
    @skill = Skill.find params[:skill_id]
  end

  def find_question
    @question = @skill.questions.find params[:question_id]
    @answers = @question.answers
  end

  def find_answer
    @answer = @answers.find params[:id]
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.haml
.answer.clearfix{id: dom_id(answer)}
  %hr
  - if can? :manage, answer
    .clearfix.manage-answer
      .manage-button-wrapper
        = link_to t(:delete), [answer.skill, answer.question, answer],
          method: :delete, confirm: t(:are_you_sure), remote: true,
          class: "manage-button"
      .manage-button-wrapper
        = link_to t(:edit), edit_skill_question_answer_path(answer.skill, answer.question, answer),
          class: "manage-button"

  %div
    = markdown answer.content
  .user-card.pull-right
    %div
      = t(:answered)
      %strong= l answer.created_at, format: :long
    %div
      = t(:by_user)
      %strong= answer.user_username

app/views/answers/_form.html.haml
#answers-form
  %h5= t(:your_answer)
  = simple_form_for [answer.skill, answer.question, answer] do |f|
    = f.input :content, as: :text, input_html: { class: "input-xxlarge", rows: 8 }, label: false,
      placeholder: t(:new_answer_placeholder),
      hint: t(:new_answer_hint_text)
    .pull-left
      = f.button :submit, t(:post_answer), class: "btn btn-primary"
    .pull-right
      = render 'answers/markdown_hint'

app/views/answers/_markdown_hint.html.haml
.markdown-hint
  = t(:text_parsed_with)
  = link_to "Markdown", "#markdown-hint", role: "button", :"data-toggle" => "modal"

  #markdown-hint.modal.hide.fade{tabindex: "-1", role: "dialog", :"aria-labelledby" => "markdown-hint-label", :"aria-hidden" => true}
    .modal-header
      %button.close{:"data-dismiss" => "modal", :"area-hidden" => true} x
      %h3#markdown-hint-label
        = t(:markdown_cheat_sheet)
    .modal-body
      %p
        = markdown MarkdownHint.example

app/views/answers/destroy.js.erb
$("#<%= dom_id(@answer) %>").fadeOut("slow", function() {
  $("#<%= dom_id(@answer) %>").remove();
});

app/views/answers/edit.html.haml
= render 'skills/menu', action: "show_question"

.tab-content
  .tab-pane.active
    = render 'answers/form', answer: @answer